### ISSUE TITLE
feat(map): Add different tile layers (floor, wall)

### ISSUE THREAD

**Issue by JeromeBollinger** [JeromeBollinger/idle-colony-game#21]
**Topic**
The player should be able to walk on floors. floors should still have a texture
The player should not be able to walk through walls. Walls would have a different texture

The floor tiles should be one layer below the walls
The wall layer can have wall tiles or "empty"/transparent tiles so the floor is apparent

**TODO**
- [ ] Add second tilemap which serves as walls
- [ ] Create at least one texture for the floor and at least one texture for the walls
- [ ] Ensure floor tilemap has a lower z-index than walls
- [ ] Unit tests
- [ ] Documentation

**Describe alternatives you've considered**
Instead of having two tilemaps stacked, we could also just have one big image in the background as floor.
However this approach seems to be less flexible
