### ISSUE TITLE
feat(concept): Add tracks

### ISSUE THREAD

**Issue by JeromeBollinger** [JeromeBollinger/idle-colony-game#24]
**Topic**
Implement track tiles on the wall map layer

**TODO**
- [ ] Draw track images for the different types
- [ ] Add horizontal tracks
- [ ] Add vertical tracks
- [ ] Add cross tracks
- [ ] Unit tests
- [ ] Documentation
