### ISSUE TITLE
feat(map): Add resource patch Ice, Iron, Uranium, Copper 

### ISSUE THREAD

**Issue by JeromeBollinger** [JeromeBollinger/idle-colony-game#26]
**Topic**
Add resource patch tile on floor tilemap

**TODO**
- [ ] Draw resource tile
- [ ] Implement different type of resources
- [ ] Add these to map import
- [ ] Unit tests
- [ ] Documentation

**Describe alternatives you've considered**
