### ISSUE TITLE
feat(map): Train can move only on tracks

### ISSUE THREAD

**Issue by JeromeBollinger** [JeromeBollinger/idle-colony-game#30]
**Topic**
The train only exists on tracks and can move only there

**TODO**
- [ ] Ensure train can only spawn on track
- [ ] Train can only move on tracks
- [ ] ignore for now that rails have a direction (we might want to have them dynamically connecting)
