### ISSUE TITLE
feat(map): player can remove walls

### ISSUE THREAD

**Issue by JeromeBollinger** [JeromeBollinger/idle-colony-game#31]
**Topic**
Player can remove walls

**TODO**
- [ ] Player can remove walls by clicking on walls
- [ ] Ensure Player can walk through mined wall (remove solid tag or similar)
- [ ] Ensure Floor can be seen under wall
